{% extends "layouts/base.phtml" %}
{% block content %}
<section>
    <div class="page_title">
        <h2 class="fl">快速充值列表</h2>
    </div>
    <table class="table">
        <tr>
            <th>充值会员</th>
            <th>充值方式</th>
            <th>充值金币数</th>
            <th>应支付金额</th>
            <th>支付状态</th>
            <th>支付宝转账交易号</th>
            <th>提交时间</th>
            <th>操作</th>
        </tr>
        <?php foreach($page->items as $item){ ?>
        <tr align="center">
            <td><?php echo $item->account; ?></td>
            <td><?php if($item->rechargeway==1){ ?>微信支付<?php }elseif($item->rechargeway==2){ ?>支付宝扫码支付<?php }else{ ?>支付宝转账支付<?php } ?></td>
            <td><?php echo $item->coin; ?></td>
            <td><?php echo $item->money; ?></td>
            <td><?php if($item->pay_status==1){ ?>未支付<?php }else{ ?>已支付<?php } ?></td>
            <td><?php echo $item->trade_num; ?></td>
            <td><?php echo date('Y-m-d H:i',$item->create_time); ?></td>
            <td>
                <?php if($item->pay_status==1){ ?><a href="/quickrecharge/edit/<?php echo $item->id; ?>" class="inner_btn">编辑</a><?php } ?>
                <a href="/quickrecharge/del/<?php echo $item->id; ?>" class="inner_btn">删除</a>
            </td>
        </tr>
        <?php } ?>
    </table>
    <aside class="paging">
        <a href="/quickrecharge/index/1">第一页</a>
        <?php for($i=$startnum;$i<=$lastnum;$i++){ ?>
            <a href="/quickrecharge/index/<?php echo $i; ?>" <?php if($i==$currentPage){ ?> class="active" <?php } ?>><?php echo $i; ?></a>
        <?php } ?>
        <a href="/quickrecharge/index/<?php echo $page->last; ?>">最后一页</a>
    </aside>
</section>
{% endblock %}