{% extends "layouts/base.phtml" %}
{% block content %}
<section>
    <ul class="ulColumn2">
        <form action="/bank/doadd" method="post">
            <li>
                <span class="item_name" style="width:150px;">银行名称：</span>
                <input type="text" class="textbox textbox_295" placeholder="银行名称" name="bank_name"/>
            </li>
            <li>
                <span class="item_name" style="width:200px;"></span>
                <input type="submit" class="link_btn" value="添加" />
            </li>
        </form>
    </ul>
</section>
{% endblock %}