{% extends "layouts/base.phtml" %}
{% block content %}
<section>
    <ul class="ulColumn2">
        <form action="/shop/doedit" method="post">
            <li>
                <span class="item_name" style="width:150px;">状态：</span>
                <label class="single_selection"><input type="radio" name="status" value="1" <?php if($shop->status==1){ ?>checked="checked"<?php } ?>>正常</label>
                <label class="single_selection"><input type="radio" name="status" value="2" <?php if($shop->status==2){ ?>checked="checked"<?php } ?>>异常</label>
            </li>
            <li>
                <span class="item_name" style="width:200px;"></span>
                <input type="hidden" name="id" value="<?php echo $shop->id; ?>" />
                <input type="submit" class="link_btn" value="编辑"/>
            </li>
        </form>
    </ul>
</section>
{% endblock %}