<div class="contentr fr">
    <div class="cr">
        <p>银行认证</p>
    </div>
    <div class="renzheng">
        <p class="  mt25 ml32">1. 请正确输入我们的工作人员给您汇入的金额</p>
        <p class=" mt15 ml32">2. 1毛钱请输入0.10，2毛钱请输入0.20，1分钱请输入0.01，2分钱输入0.02，以此类推</p>
        <p class=" mt25 ml32" style="color:#cf4503">PS：星期一到星期五为工作日，星期六星期日为非工作日。</p>
    </div>
    <div class="cr_1 ml90 mt30" >
        <form action="" method="post">
            <div class="mt25">
                <label class="xlabel">汇入金额:</label>
                <input type="text" name="remittance" class="kuang2"/> 元
            </div>
            <input class="submit_reg ml160 mt25" type="submit" value="验证" />
        </form>
    </div>
</div>