<div class="contentr-r fr">
    <div class="cr-r">
        <p>账号充值</p>
    </div >
    <div class="zh-b">
        <div class="zh ml50 f18">
            <div class="zh-p ml50 f18 "> 帐号充值主要用于发布任务，被接手后，这些钱就转回到您的店铺支付宝了。淘易信为您提供了快捷的充值方式，可用支付宝充值，或者选择微信充值,安全可靠，快捷简单，及时到账。 </div>
        </div>
        <div class="mt30">
            <span class="ml50"><i>如充值遇到问题请联系客服QQ564846700</i><img  class=" ml5" src="/static/images/qq2.png" /></span>
        </div>
        <form action="/user/selectmethod" method="post">
            <div class=" ml60 mt25">
                <span class="f16">充值金额:</span>
                <input class="ml20 input-z" name="coin" type="text" value="100" /><span>金币</span>
            </div>
            <div class=" ml145 mt15">
                <button type="submit" id="paySend" class="gwyy_btn">充值</button>
            </div>
        </form>
    </div>
</div>