<div class="contentr fr">
    <div class="cr">
        <p>交易记录</p>
    </div>
    <div class="qishiriqi mt25 ml32">
        <span class="ml14">起始日期: </span><input type="text" class="kuang-x" /> <span>至</span> <input type="text" class="kuang-x" />
        <span class="ml32">用户名：</span><input class=" kuang-x" type="text" /><input type="submit" name=" button1" value="查询" id="button" class="ml14"/></div>
    <div leftmargin=20 topmargin=20 class=" ml32 mt25" >
        <table width="890" border="1" bordercolor="#dddddd" cellspacing="0" cellpadding="0" class="f14">

            <tr >
                <td width="174" height="60" align="center" bgcolor="#f0f0f0">流水号</td>
                <td width="116" height="40" align="center" bgcolor="#f0f0f0">类型</td>
                <td width="102" height="40" align="center" bgcolor="#f0f0f0">金额变动</td>
                <td width="149" height="40" align="center" bgcolor="#f0f0f0">日期</td>
                <td width="337" height="40" align="center" bgcolor="#f0f0f0">备注</td>
            </tr>
            <tr >
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">会员</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">1天试用</td>
            </tr>
            <tr >
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">会员</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">3454486任务12小时未审核，自动取消任务奖</td>
            </tr>
            <tr >
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">任何奖励</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">1天试用</td>
            </tr>
            <tr >
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">积分</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">3454486任务12小时未审核，自动取消任务奖</td>
            </tr >
            <tr>
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">任何奖励</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">3454486任务12小时未审核，自动取消任务奖</td>
            </tr>
            <tr >
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">罚款</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">120积分,兑换4金币</td>
            </tr>
            <tr >
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">充值</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">120积分,兑换4金币</td>
            </tr >
            <tr>
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">充值</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">120积分,兑换4金币</td>
            </tr>
            <tr >
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">充值</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">120积分,兑换4金币</td>
            </tr >
            <tr>
                <td height="40" align="center">251976144</td>
                <td height="40" align="center">充值</td>
                <td height="40" align="center">0</td>
                <td height="40" align="center">2016-01-01</td>
                <td height="40" align="center">120积分,兑换4金币</td>
            </tr>

        </table>


    </div>
</div>