<!--密保找回密码-->
<div id="mibao">
    <div class="mibao">
        <p>修改密码</p>
        <div class="wenti">
            <form action="/index/changepassword" method="post" >
                <div class="feld">
                    <div class="mt25">
                        <label class="label">新密码:</label>
                        <input type="password" name="password" class="kuang1" style="margin-left:30px;" placeholder="数字、大小写字母或下划线，6-32个字符"/>
                    </div>
                </div>
                <div class="feld">
                    <div class="mt25">
                        <label class="label">重复新密码:</label>
                        <input type="password" name="repassword" class="kuang1" />
                    </div>
                </div>
                <input type="hidden" value="<?php echo $account; ?>" name="account" />
                <input type="hidden" value="<?php echo $answer1; ?>" name="answer1" />
                <input type="hidden" value="<?php echo $answer2; ?>" name="answer2" />
                <input type="submit" value="提交" class="tijiao  ml80 mt30"/>
            </form>
        </div>
    </div>
</div>
</div>