<!--密保找回密码-->
<div id="mibao">
    <div class="mibao">
        <p>请输入要找回密码的用户名</p>
        <div class="wenti">
            <form action="/index/confirmquestion" method="post" >
                <div class="feld">
                    <div class="mt25">
                        <label class="label">用户名:</label>
                        <input type="text" name="account" class="kuang1" placeholder="请输入用户名" />
                    </div>
                </div>
                <input type="submit" value="提交" class="tijiao  ml80 mt30"/>
            </form>
            <span class=" mt30 ml80"><a href="#">电子邮件重置密码</a></span>
            <span class=" mt30"><a href="#">手机短信重置密码</a></span>
        </div>
    </div>
</div>
</div>