<div class="contentr fr">
    <div class="cr">
        <p >推荐说明</p>
    </div>
    <div class="ts ml32 mt30">
        <h1 class="tuijian">奖励方式:</h1>
        <p class="f16 mt10"><span class="tjwz f16">一次性奖励:</span>是指成功推荐一位有效淘客或者商家按照您的推广员级别获得相应的奖励金额</p>
        <p class="f16 mt10"><span class="tjwz f16">提成式奖励:</span>是指您推的任意一位商家或淘客，他们每放一单或每接一单您都能获得相应的奖励，此奖励是永久生效的。</p>
        <p class="f16 mt10">淘客推广方案(有效刷手：即接单并完成做单满15单的淘客)</p>
        <p class="f16 mt10">商家推广方案(有效商家：放单且完成的任务满15单的商家)</p>
    </div>

    <div leftmargin=20 topmargin=20 class=" ml32" >
        <table width="795" border="1" bordercolor="#dddddd" cellspacing="0" cellpadding="0" class="f16">

            <tr >
                <td width="216" height="60"  align="center" bgcolor="#f0f0f0">推广员分类</td>
                <td width="197" height="60" align="center" bgcolor="#f0f0f0">推广有效淘客数</td>
                <td width="163" height="60" align="center" bgcolor="#f0f0f0">一次性奖励金额</td>
                <td width="209" height="60" align="center" bgcolor="#f0f0f0">提成式奖励金额</td>
            </tr>
            <tr >
                <td height="40" align="center">淘客</td>
                <td height="40" align="center">0-10</td>
                <td height="40" align="center">50金币/人</td>
                <td height="40" align="center">0元/单</td>
            </tr>
            <tr >
                <td height="40" align="center">商家</td>
                <td height="40" align="center">0-10</td>
                <td height="40" align="center">50金币/人</td>
                <td height="40" align="center">0.5元/单</td>
            </tr>

        </table>

    </div>
</div>