<div class="contentr fr">
    <div class="cr">
        <p >奖励排行</p>
    </div>



    <table  class=" ml120 mt25" width="600" border="1" cellspacing="0" cellpadding="0" bordercolor="#dddddd" >
        <tr style=" border-bottom:#FFF; border-right:#edf2ff;">
            <td width="189" height="50" align="center" bgcolor="#f0f0f0">排名</td>
            <td width="197" align="center" bgcolor="#f0f0f0">用户名称</td>
            <td width="206" align="center" bgcolor="#f0f0f0" style=" border-right-color:#dddddd ">获得的返现金额</td>
        </tr>
        <tr style=" border-top:#FFF; border-right:#FFF;">
            <td height="50" align="center">1</td>
            <td align="center">meigong123</td>
            <td align="center" style=" border-right-color:#dddddd "><em>666元</em></td>
        </tr>
        <tr style=" border-top:#FFF; border-right:#FFF;">
            <td height="50" align="center">2</td>
            <td align="center">meigong123</td>
            <td align="center" style=" border-right-color:#dddddd "><em>666元</em></td>
        </tr>
        <tr style=" border-top:#FFF; border-right:#FFF;">
            <td height="50" align="center">3</td>
            <td align="center">meigong123</td>
            <td align="center" style=" border-right-color:#dddddd "><em>666元</em></td>
        </tr>
        <tr style=" border-top:#FFF; border-right:#FFF;">
            <td height="50" align="center">4</td>
            <td align="center">meigong123</td>
            <td align="center" style=" border-right-color:#dddddd "><em>666元</em></td>
        </tr>
        <tr style=" border-top:#FFF; border-right:#FFF;">
            <td height="50" align="center">5</td>
            <td align="center">meigong123</td>
            <td align="center" style=" border-right-color:#dddddd "><em>666元</em></td>
        </tr>
        <tr style=" border-top:#FFF; border-right:#FFF;">
            <td height="50" align="center">6</td>
            <td align="center">meigong123</td>
            <td align="center" style=" border-right-color:#dddddd "><em>666元</em></td>
        </tr>
        <tr style=" border-top:#FFF; border-right:#FFF;">
            <td height="50" align="center">7</td>
            <td align="center">meigong123</td>
            <td align="center" style=" border-right-color:#dddddd "><em>666元</em></td>
        </tr>
    </table>
</div>