{% extends "layouts/base.phtml" %}
{% block content %}
    <section>
        <ul class="ulColumn2">
            <form action="/member/doedit" method="post">
            <li>
                <span class="item_name" style="width:120px;">管理员名：</span>
                <input type="text" class="textbox textbox_295" placeholder="用户名" name="name" value="{{ memberone.name }}" />
            </li>
            <li>
                <span class="item_name" style="width:120px;">管理员密码：</span>
                <input type="text" class="textbox textbox_295" placeholder="不修改密码请留空" name="password" />
            </li>
            <li>
                <input type="hidden" name="id" value="{{ memberone.id }}" />
                <span class="item_name" style="width:150px;"></span>
                <input type="submit" class="link_btn"/>
            </li>
            </form>
        </ul>
    </section>
{% endblock %}