<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <META NAME="Generator" CONTENT="EditPlus">
    <META NAME="Author" CONTENT="">
    <META NAME="Keywords" CONTENT="">
    <META NAME="Description" CONTENT="">
    <script type="text/javascript" src="/static/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery.SuperSlide.2.1.1.js"></script>
    <script type="text/javascript" src="/static/js/jquery.zclip.min.js"></script>
    <title>会员信息</title>
    <link href="/static/css/liebiao.css" rel="stylesheet" type="text/css" />
    <script Language="javascript">
        function a(x,y,color)
        {document.write("<img border='0' style='position: absolute; left: "+(x+20)+"; top: "+(y+20)+";background-color: "+color+"' src='px.gif' width=1 height=1>")}
    </script>
</head>

<body leftmargin=20 topmargin=20>
<!--top开始-->
<div id="top">
    <div class="top auto">
        <?php if(!$this->session->has('uname')){ ?>
            <div class="huanying fl" id="noname">
                <p> <span class="midn"></span>您好,欢迎来到右右电商服务平台！<a href="#">[ 登录 ]</a><a href="/index/reg"> [ 免费注册 ]</a></p>
            </div>
        <?php }else{ ?>
            <div class="huanying fl" id="isname">
                <p> <span class="midn"></span>您好,<span><a href="/user/index"><?php echo $this->session->get('uname'); ?></a><a href="/index/logout"> [ 安全退出 ]</a></span></p>
            </div>
        <?php } ?>
        <div class="jiaru fr">
            <ul>
                <li><a <?php if($this->session->has('uname')){ ?> href="/user/index" <?php }else{ ?> href="/" <?php } ?>>我的账户</a></li>
                <li><a href="#">帮助中心</a></li>
                <li class="phone">手机版</li>
                <li class="wei">微信端
            </ul>
        </div>
    </div>
</div>
<!--logo开始-->
<div class="denglu auto">
    <div class="logo fl"><img src="/static/images/logo.jpg"></div>
</div>
<!--导航开始-->
<div id="nav">
    <div class=" dh auto">
        <ul class="auto">
            <li><a href="/">首页</a></li>
            <li><a <?php if($this->session->has('uname')){ ?> href="/task/index" <?php }else{ ?> href="/" <?php } ?> >任务大厅</a></li>
            <li><a <?php if($this->session->has('uname')){ ?> href="/user/index" <?php }else{ ?> href="/" <?php } ?> >会员中心</a></li>
            <li><a <?php if($this->session->has('uname')){ ?> href="/promotion/index" <?php }else{ ?> href="/" <?php } ?> >我的推广</a></li>
            <li><a <?php if($this->session->has('uname')){ ?> href="/user/recharge" <?php }else{ ?> href="/" <?php } ?> >会员充值</a></li>
            <li><a href="lianxikefu.html">联系客服</a></li>
        </ul>
    </div>
</div>
<!--银行认证-->
<div id="content" class="auto mt25">

    <!--content左边-->
    <div class="contentl fl">
        <p><img src="/static/images/huiyuan.jpg" /></p>
        <ul class="ul1">
            <?php if($operation=='userinfo'){ ?><li style="color:#f7941d;">会员信息</li><?php }else{ ?><li><a href="/user/index">会员信息</a></li><?php } ?>
            <?php if($operation=='quickrecharge'){ ?><li style="color:#f7941d;">快速充值</li><?php }else{ ?><li><a href="/user/recharge">快速充值</a></li><?php } ?>
            <?php if($operation=='rewarddetail'){ ?><li style="color:#f7941d;">奖励明细</li><?php }else{ ?><li><a href="/user/reward">奖励明细</a></li><?php } ?>
            <?php if($operation=='returnmoney'){ ?><li style="color:#f7941d;">返款设置</li><?php }else{ ?><li><a href="/user/returnmoney">返款设置</a></li><?php } ?>
            <?php if($operation=='bankcertification'){ ?><li style="color:#f7941d;">银行认证</li><?php }else{ ?><li><a href="/user/bankcertification">银行认证</a></li><?php } ?>
            <?php if($this->session->get('utype')==1){ if($operation=='bindshop'){ ?><li style="color:#f7941d;">绑定商铺</li><?php }else{ ?><li><a href="/user/bindshop">绑定商铺</a></li><?php } } ?>
            <?php if($this->session->get('utype')==2){ if($operation=='bindtb'){ ?><li style="color:#f7941d;">绑定淘宝号</li><?php }else{ ?><li><a href="/user/bindtb">绑定淘宝号</a></li><?php } } ?>
            <?php if($operation=='coinexchange'){ ?><li style="color:#f7941d;">金币兑现</li><?php }else{ ?><li><a href="/user/coinexchange">金币兑现</a></li><?php } ?>
            <?php if($this->session->get('utype')==1){ if($operation=='buyrelease'){ ?><li style="color:#f7941d;">购买发布点</li><?php }else{ ?><li><a href="/user/buyrelease">购买发布点</a></li><?php } } ?>
            <?php if($operation=='safesetting'){ ?><li style="color:#f7941d;">安全设置</li><?php }else{ ?><li><a href="/user/safesetting">安全设置</a></li><?php } ?>
            <li><a href="/promotion/index">我的推广</a></li>
            <?php if($operation=='transactionrecord'){ ?><li style="color:#f7941d;">交易记录</li><?php }else{ ?><li><a href="/user/transactionrecord">交易记录</a></li><?php } ?>
        </ul>
    </div>

    <!--content右边-->
    <?php echo $this->getContent(); ?>

</div>
<!--底部开始-->
<div id="footer">
    <div class="footer auto">
        <div class="footer_l fl">
            <div class="footer-about fl">
                <h2 class="title">关于右右网</h2>
            </div>
            <div class="footer-help fl">
                <h2 class="title">帮助中心</h2>
            </div>
            <div class="footer-safe fl">
                <h2 class="title">安全保障</h2>
            </div>
            <!--<div class="footer-help fl"><h3>帮助中心</h3></div>-->
        </div>
        <div class="footer_r fr">
            <div class="erweima fl"> <img src="/static/images/erweima1.png" />
                <h3 class="ml20">移动端下载</h3>
            </div>
            <div class="erweima fl"> <img src="/static/images/erweima2.png" />
                <h3 class="ml20">微信公众号</h3>
            </div>
            <div class="youyou fr">
                <p ><img src="/static/images/logo.png"/></p>
                <p >全国服务热线：</p>
                <p>人工服务时间：8.00-12.00</p>
            </div>
        </div>
    </div>
</div>
</body>
</html>
