<div class=" ctr fr">
    <div class="cr">
        <p >发布类型</p>
    </div>
    <div>
        <form action="/task/selecttpl" class=" mt45" method="post">
            <div>
                <label class="xlabel_2">任务平台:</label>
                <select name="platform" class=" kuang3">
                    <option value="1">淘宝</option>
                    <option value="2">京东</option>
                    <option value="1">阿里巴巴</option>
                </select>
            </div>
            <div>
                <label class="xlabel_2 mt25">任务方式:</label>
                <select name="type" class=" kuang3">
                    <option value="1">电脑单</option>
                    <option value="2">手机单</option>
                    <option value="3">浏览单</option>
                    <option value="4">秒拍单</option>
                </select>
            </div>
            <div><input type="submit" value="确定" class=" submit_reg2 ml145 mt25">
            </div>
        </form>
    </div>
</div>