{% extends "layouts/base.phtml" %}
{% block content %}
<section>
    <div class="page_title">
        <h2 class="fl">银行认证申请列表</h2>
    </div>
    <table class="table">
        <tr>
            <th>流水号</th>
            <th>申请认证会员</th>
            <th>银行卡号</th>
            <th>银行名称</th>
            <th>真实姓名</th>
            <th>手机号</th>
            <th>申请提交时间</th>
            <th>验证状态</th>
            <th>处理日期</th>
            <th>汇入金额</th>
            <th>操作</th>
        </tr>
        <?php foreach($page->items as $item){ ?>
        <tr align="center">
            <td><?php echo $item->serial_num; ?></td>
            <td><?php echo $item->account; ?></td>
            <td><?php echo $item->bankcard_num; ?></td>
            <td><?php echo $item->bank_name; ?></td>
            <td><?php echo $item->real_name; ?></td>
            <td><?php echo $item->mobile_num; ?></td>
            <td><?php echo date('Y-m-d H:i',$item->create_time); ?></td>
            <td><?php if($item->verification==1){ ?>未验证<?php }else{ ?>已验证<?php } ?></td>
            <td><?php if($item->handle_time){ echo date('Y-m-d H:i',$item->handle_time); }else{ ?>未处理<?php } ?></td>
            <td><?php if($item->remittance){ ?><?php echo $item->remittance;  ?>元<?php }else{ ?>未汇款<?php } ?></td>
            <td>
                <a href="/bankapply/edit/<?php echo $item->id; ?>" class="inner_btn">编辑</a>
                <a href="/bankapply/del/<?php echo $item->id; ?>" class="inner_btn">删除</a>
            </td>
        </tr>
        <?php } ?>
    </table>
    <aside class="paging">
        <a href="/bankapply/index/1">第一页</a>
        <?php for($i=$startnum;$i<=$lastnum;$i++){ ?>
            <a href="/bankapply/index/<?php echo $i; ?>" <?php if($i==$currentPage){ ?> class="active" <?php } ?>><?php echo $i; ?></a>
        <?php } ?>
        <a href="/bankapply/index/<?php echo $page->last; ?>">最后一页</a>
    </aside>
</section>
{% endblock %}