{% extends "layouts/base.phtml" %}
{% block content %}
<section>
    <div class="page_title">
        <h2 class="fl">充值卡列表</h2>
    </div>
    <table class="table">
        <tr>
            <th>充值卡卡号</th>
            <th>价值</th>
            <th>是否被使用</th>
            <th>充值卡添加时间</th>
            <th>操作</th>
        </tr>
        <?php foreach($page->items as $item){ ?>
        <tr align="center">
            <td><?php echo $item->card_num; ?></td>
            <td><?php echo $item->gcoin_num; ?>金币</td>
            <td><?php if($item->isuse==1){ ?>未被使用<?php }elseif($item->isuse==2){ ?>已被使用<?php } ?></td>
            <td><?php echo date('Y-m-d',$item->create_time); ?></td>
            <td>
                <a href="/rechargecard/del/<?php echo $item->id; ?>" class="inner_btn">删除</a>
            </td>
        </tr>
        <?php } ?>
    </table>
    <aside class="paging">
        <a href="/rechargecard/index/1">第一页</a>
        <?php for($i=$startnum;$i<=$lastnum;$i++){ ?>
            <a href="/rechargecard/index/<?php echo $i; ?>" <?php if($i==$currentPage){ ?> class="active" <?php } ?>><?php echo $i; ?></a>
        <?php } ?>
        <a href="/rechargecard/index/<?php echo $page->last; ?>">最后一页</a>
    </aside>
</section>
{% endblock %}