{% extends "layouts/base.phtml" %}
{% block content %}
<section>
    <div class="page_title">
        <h2 class="fl">文章类型列表</h2>
    </div>
    <table class="table">
        <tr>
            <th>类型id</th>
            <th>类型名</th>
            <th>操作</th>
        </tr>
        {% for v in page.items %}
        <tr align="center">
            <td>{{ v.id|e }}</td>
            <td>{{ v.name|e }}</td>
            <td>
                <a href="/newstype/edit/{{ v.id }}" class="inner_btn">编辑</a>
                <a href="/newstype/del/{{ v.id }}" class="inner_btn">删除</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <aside class="paging">
        <a href="/newstype/index/1">第一页</a>
        {% for num in startnum..lastnum %}
        <a href="/newstype/index/{{ num }}" {% if currentPage==num %} class="active" {% endif %}>{{ num }}</a>
        {% endfor %}
        <a href="/newstype/index/{{ page.last }}">最后一页</a>
    </aside>
</section>
{% endblock %}